cars=['bmw','audi','toyota','sabaru']
print("Here is the original list:")
print(cars)
print("\nHere is the sorted list:")
print(sorted(cars))
print("Here is the original list:")
print(cars)
cars.reverse()
print(cars)
print(cars.reverse())